CREATE TABLE IF NOT EXISTS todos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tasks (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TODO_ID INT,
    CONSTRAINT FK_TASK_TODO FOREIGN KEY (TODO_ID) REFERENCES todos(ID)
    ) ENGINE=InnoDB;
